[2024-11-26T01:48:40.318+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:48:40.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:48:40.319+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:48:40.319+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:48:40.322+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:48:40.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:48:40.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:48:40.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.020 seconds
[2024-11-26T01:49:11.175+0000] {processor.py:186} INFO - Started process (PID=74) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:49:11.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:49:11.177+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:49:11.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:49:11.179+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:49:11.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:49:11.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:49:11.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T01:49:41.606+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:49:41.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:49:41.608+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:49:41.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:49:41.610+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:49:41.609+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:49:41.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:49:41.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.013 seconds
[2024-11-26T01:50:11.987+0000] {processor.py:186} INFO - Started process (PID=110) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:50:11.988+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:50:11.989+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:50:11.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:50:11.992+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:50:11.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:50:11.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:50:12.005+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.024 seconds
[2024-11-26T01:50:42.264+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:50:42.265+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:50:42.266+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:50:42.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:50:42.268+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:50:42.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:50:42.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:50:42.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T01:51:12.573+0000] {processor.py:186} INFO - Started process (PID=145) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:51:12.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:51:12.575+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:51:12.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:51:12.577+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:51:12.577+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:51:12.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:51:12.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.016 seconds
[2024-11-26T01:51:43.183+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:51:43.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:51:43.186+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:51:43.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:51:43.196+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:51:43.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:51:43.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:51:43.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.035 seconds
[2024-11-26T01:52:13.563+0000] {processor.py:186} INFO - Started process (PID=181) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:52:13.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:52:13.566+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:52:13.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:52:13.568+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:52:13.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:52:13.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:52:13.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.015 seconds
[2024-11-26T01:52:43.990+0000] {processor.py:186} INFO - Started process (PID=206) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:52:43.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:52:43.991+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:52:43.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:52:43.993+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:52:43.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:52:43.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:52:44.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.015 seconds
[2024-11-26T01:53:14.296+0000] {processor.py:186} INFO - Started process (PID=232) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:53:14.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:53:14.297+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:53:14.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:53:14.300+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:53:14.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:53:14.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:53:14.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.016 seconds
[2024-11-26T01:53:44.808+0000] {processor.py:186} INFO - Started process (PID=253) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:53:44.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:53:44.810+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:53:44.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:53:44.812+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:53:44.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:53:44.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:53:44.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.017 seconds
[2024-11-26T01:54:15.906+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:54:15.907+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:54:15.908+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:54:15.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:54:15.912+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:54:15.911+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:54:15.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:54:15.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.025 seconds
[2024-11-26T01:54:46.190+0000] {processor.py:186} INFO - Started process (PID=299) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:54:46.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:54:46.192+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:54:46.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:54:46.198+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:54:46.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:54:46.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:54:46.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.017 seconds
[2024-11-26T01:55:16.597+0000] {processor.py:186} INFO - Started process (PID=320) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:55:16.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:55:16.600+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:55:16.599+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:55:16.605+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:55:16.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:55:16.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:55:16.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.017 seconds
[2024-11-26T01:55:47.195+0000] {processor.py:186} INFO - Started process (PID=349) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:55:47.195+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:55:47.196+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:55:47.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:55:47.204+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:55:47.203+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:55:47.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:55:47.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.027 seconds
[2024-11-26T01:56:18.251+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:56:18.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:56:18.254+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:56:18.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:56:18.256+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:56:18.255+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:56:18.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:56:18.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.015 seconds
[2024-11-26T01:56:48.720+0000] {processor.py:186} INFO - Started process (PID=398) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:56:48.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:56:48.722+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:56:48.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:56:48.724+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:56:48.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:56:48.724+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:56:48.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.015 seconds
[2024-11-26T01:57:19.326+0000] {processor.py:186} INFO - Started process (PID=425) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:57:19.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:57:19.328+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:57:19.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:57:19.338+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:57:19.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:57:19.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:57:19.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.033 seconds
[2024-11-26T01:57:49.477+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:57:49.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:57:49.480+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:57:49.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:57:49.484+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:57:49.483+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:57:49.486+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:57:49.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.020 seconds
[2024-11-26T01:58:19.811+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:58:19.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:58:19.813+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:58:19.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:58:19.815+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:58:19.814+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:58:19.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:58:19.823+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T01:58:50.187+0000] {processor.py:186} INFO - Started process (PID=499) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:58:50.188+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:58:50.189+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:58:50.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:58:50.191+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:58:50.190+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:58:50.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:58:50.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.015 seconds
[2024-11-26T01:59:20.578+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:59:20.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:59:20.580+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:59:20.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:59:20.581+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:59:20.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:59:20.582+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:59:20.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.013 seconds
[2024-11-26T01:59:51.246+0000] {processor.py:186} INFO - Started process (PID=537) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:59:51.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T01:59:51.247+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:59:51.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:59:51.249+0000] {logging_mixin.py:190} INFO - [2024-11-26T01:59:51.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T01:59:51.250+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T01:59:51.257+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.013 seconds
[2024-11-26T02:00:21.954+0000] {processor.py:186} INFO - Started process (PID=556) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:00:21.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:00:21.955+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:00:21.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:00:21.958+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:00:21.957+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:00:21.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:00:21.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.017 seconds
[2024-11-26T02:00:52.462+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:00:52.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:00:52.463+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:00:52.463+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:00:52.466+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:00:52.465+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:00:52.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:00:52.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T02:01:23.642+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:01:23.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:01:23.643+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:01:23.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:01:23.646+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:01:23.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:01:23.646+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:01:23.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T02:01:53.951+0000] {processor.py:186} INFO - Started process (PID=631) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:01:53.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:01:53.952+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:01:53.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:01:53.955+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:01:53.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:01:53.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:01:53.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.020 seconds
[2024-11-26T02:02:24.351+0000] {processor.py:186} INFO - Started process (PID=649) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:02:24.352+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:02:24.352+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:02:24.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:02:24.355+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:02:24.355+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:02:24.356+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:02:24.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.019 seconds
[2024-11-26T02:02:54.601+0000] {processor.py:186} INFO - Started process (PID=667) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:02:54.602+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:02:54.602+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:02:54.602+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:02:54.604+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:02:54.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:02:54.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:02:54.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T02:03:25.745+0000] {processor.py:186} INFO - Started process (PID=685) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:03:25.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:03:25.746+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:03:25.746+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:03:25.748+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:03:25.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:03:25.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:03:25.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T02:03:56.920+0000] {processor.py:186} INFO - Started process (PID=703) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:03:56.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:03:56.922+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:03:56.921+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:03:56.923+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:03:56.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:03:56.924+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:03:56.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.016 seconds
[2024-11-26T02:04:27.477+0000] {processor.py:186} INFO - Started process (PID=720) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:04:27.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:04:27.478+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:04:27.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:04:27.480+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:04:27.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:04:27.480+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:04:27.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.013 seconds
[2024-11-26T02:04:58.894+0000] {processor.py:186} INFO - Started process (PID=738) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:04:58.896+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:04:58.897+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:04:58.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:04:58.919+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:04:58.909+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:04:58.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:04:58.935+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.048 seconds
[2024-11-26T02:05:29.139+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:05:29.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:05:29.141+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:05:29.141+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:05:29.150+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:05:29.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:05:29.150+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:05:29.160+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.024 seconds
[2024-11-26T02:05:59.597+0000] {processor.py:186} INFO - Started process (PID=774) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:05:59.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:05:59.598+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:05:59.598+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:05:59.600+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:05:59.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:05:59.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:05:59.607+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.012 seconds
[2024-11-26T02:06:30.829+0000] {processor.py:186} INFO - Started process (PID=792) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:06:30.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:06:30.830+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:06:30.830+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:06:30.832+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:06:30.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:06:30.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:06:30.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.015 seconds
[2024-11-26T02:07:01.431+0000] {processor.py:186} INFO - Started process (PID=809) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:07:01.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:07:01.434+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:07:01.433+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:07:01.438+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:07:01.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:07:01.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:07:01.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.024 seconds
[2024-11-26T02:07:31.677+0000] {processor.py:186} INFO - Started process (PID=827) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:07:31.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:07:31.678+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:07:31.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:07:31.680+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:07:31.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:07:31.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:07:31.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T02:08:02.176+0000] {processor.py:186} INFO - Started process (PID=845) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:08:02.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:08:02.178+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:08:02.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:08:02.180+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:08:02.179+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:08:02.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:08:02.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.016 seconds
[2024-11-26T02:08:32.803+0000] {processor.py:186} INFO - Started process (PID=863) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:08:32.803+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:08:32.803+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:08:32.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:08:32.805+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:08:32.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:08:32.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:08:32.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.013 seconds
[2024-11-26T02:09:03.063+0000] {processor.py:186} INFO - Started process (PID=881) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:09:03.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:09:03.064+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:09:03.064+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:09:03.066+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:09:03.065+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:09:03.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:09:03.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.016 seconds
[2024-11-26T02:09:33.586+0000] {processor.py:186} INFO - Started process (PID=899) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:09:33.587+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:09:33.587+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:09:33.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:09:33.590+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:09:33.589+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:09:33.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:09:33.598+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T02:10:03.981+0000] {processor.py:186} INFO - Started process (PID=917) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:10:03.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:10:03.982+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:10:03.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:10:03.988+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:10:03.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:10:03.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:10:03.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.019 seconds
[2024-11-26T02:10:34.545+0000] {processor.py:186} INFO - Started process (PID=935) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:10:34.546+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:10:34.546+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:10:34.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:10:34.550+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:10:34.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:10:34.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:10:34.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.015 seconds
[2024-11-26T02:11:05.021+0000] {processor.py:186} INFO - Started process (PID=953) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:11:05.021+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:11:05.022+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:11:05.022+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:11:05.025+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:11:05.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:11:05.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:11:05.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.014 seconds
[2024-11-26T02:11:35.762+0000] {processor.py:186} INFO - Started process (PID=971) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:11:35.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:11:35.763+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:11:35.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:11:35.766+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:11:35.765+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:11:35.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:11:35.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.012 seconds
[2024-11-26T02:12:06.318+0000] {processor.py:186} INFO - Started process (PID=989) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:12:06.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:12:06.322+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:12:06.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:12:06.326+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:12:06.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:12:06.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:12:06.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.020 seconds
[2024-11-26T02:12:37.616+0000] {processor.py:186} INFO - Started process (PID=1016) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:12:37.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:12:37.617+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:12:37.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:12:37.620+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:12:37.620+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:12:37.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:12:37.627+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.015 seconds
[2024-11-26T02:13:08.623+0000] {processor.py:186} INFO - Started process (PID=1034) to work on /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:13:08.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/no_use/django_sample.py for tasks to queue
[2024-11-26T02:13:08.624+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:13:08.624+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:13:08.628+0000] {logging_mixin.py:190} INFO - [2024-11-26T02:13:08.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/no_use/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/no_use/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-26T02:13:08.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/no_use/django_sample.py
[2024-11-26T02:13:08.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/no_use/django_sample.py took 0.016 seconds
