[2024-11-22T08:50:18.964+0000] {processor.py:153} INFO - Started process (PID=53) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:50:18.966+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:50:18.969+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:50:18.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:50:19.001+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:50:18.995+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:50:19.003+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:50:19.252+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.294 seconds
[2024-11-22T08:50:49.765+0000] {processor.py:153} INFO - Started process (PID=120) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:50:49.782+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:50:49.800+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:50:49.800+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:50:49.864+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:50:49.854+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:50:49.876+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:50:50.054+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.301 seconds
[2024-11-22T08:51:20.808+0000] {processor.py:153} INFO - Started process (PID=194) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:51:20.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:51:20.831+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:51:20.828+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:51:20.851+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:51:20.850+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:51:20.852+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:51:20.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.161 seconds
[2024-11-22T08:51:51.407+0000] {processor.py:153} INFO - Started process (PID=275) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:51:51.410+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:51:51.411+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:51:51.411+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:51:51.418+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:51:51.416+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:51:51.418+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:51:51.446+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.047 seconds
[2024-11-22T08:52:21.887+0000] {processor.py:153} INFO - Started process (PID=365) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:52:21.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:52:21.889+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:52:21.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:52:21.893+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:52:21.892+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:52:21.894+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:52:21.913+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.031 seconds
[2024-11-22T08:52:52.116+0000] {processor.py:153} INFO - Started process (PID=439) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:52:52.117+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:52:52.119+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:52:52.118+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:52:52.123+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:52:52.121+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:52:52.124+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:52:52.150+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.042 seconds
[2024-11-22T08:53:23.125+0000] {processor.py:153} INFO - Started process (PID=529) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:53:23.131+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:53:23.133+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:53:23.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:53:23.141+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:53:23.138+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:53:23.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:53:23.181+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.065 seconds
[2024-11-22T08:53:53.823+0000] {processor.py:153} INFO - Started process (PID=617) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:53:53.824+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:53:53.826+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:53:53.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:53:53.830+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:53:53.829+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:53:53.832+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:53:53.851+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.034 seconds
[2024-11-22T08:54:23.888+0000] {processor.py:153} INFO - Started process (PID=692) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:54:23.890+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:54:23.890+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:54:23.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:54:23.903+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:54:23.902+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:54:23.906+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:54:23.925+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.044 seconds
[2024-11-22T08:54:54.794+0000] {processor.py:153} INFO - Started process (PID=780) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:54:54.796+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:54:54.797+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:54:54.797+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:54:54.802+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:54:54.800+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:54:54.803+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:54:54.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.033 seconds
[2024-11-22T08:55:25.498+0000] {processor.py:153} INFO - Started process (PID=870) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:55:25.501+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:55:25.502+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:55:25.501+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:55:25.506+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:55:25.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:55:25.506+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:55:25.522+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.030 seconds
[2024-11-22T08:55:56.139+0000] {processor.py:153} INFO - Started process (PID=944) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:55:56.140+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:55:56.140+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:55:56.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:55:56.142+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:55:56.141+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:55:56.143+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:55:56.164+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.028 seconds
[2024-11-22T08:56:27.147+0000] {processor.py:153} INFO - Started process (PID=1034) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:56:27.149+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:56:27.150+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:56:27.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:56:27.154+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:56:27.153+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:56:27.154+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:56:27.181+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.038 seconds
[2024-11-22T08:56:58.025+0000] {processor.py:153} INFO - Started process (PID=1124) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:56:58.028+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:56:58.030+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:56:58.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:56:58.037+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:56:58.035+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:56:58.037+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:56:58.057+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.038 seconds
[2024-11-22T08:57:28.842+0000] {processor.py:153} INFO - Started process (PID=1214) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:57:28.844+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:57:28.844+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:57:28.844+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:57:28.847+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:57:28.847+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:57:28.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:57:28.863+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.024 seconds
[2024-11-22T08:57:59.484+0000] {processor.py:153} INFO - Started process (PID=1288) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:57:59.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:57:59.487+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:57:59.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:57:59.491+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:57:59.490+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:57:59.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:57:59.512+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.035 seconds
[2024-11-22T08:58:30.069+0000] {processor.py:153} INFO - Started process (PID=1377) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:58:30.070+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:58:30.070+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:58:30.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:58:30.074+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:58:30.073+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:58:30.075+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:58:30.091+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.027 seconds
[2024-11-22T08:59:00.926+0000] {processor.py:153} INFO - Started process (PID=1467) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:59:00.927+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:59:00.928+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:59:00.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:59:00.931+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:59:00.930+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:59:00.931+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:59:00.948+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.028 seconds
[2024-11-22T08:59:31.755+0000] {processor.py:153} INFO - Started process (PID=1557) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T08:59:31.757+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T08:59:31.758+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:59:31.758+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T08:59:31.762+0000] {logging_mixin.py:137} INFO - [2024-11-22T08:59:31.762+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T08:59:31.763+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T08:59:31.794+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.044 seconds
[2024-11-22T09:00:01.822+0000] {processor.py:153} INFO - Started process (PID=1631) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:00:01.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:00:01.824+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:00:01.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:00:01.827+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:00:01.826+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:00:01.827+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:00:01.844+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.027 seconds
[2024-11-22T09:00:32.242+0000] {processor.py:153} INFO - Started process (PID=1720) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:00:32.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:00:32.245+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:00:32.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:00:32.249+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:00:32.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:00:32.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:00:32.270+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.033 seconds
[2024-11-22T09:01:19.149+0000] {processor.py:153} INFO - Started process (PID=37) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:01:19.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:01:19.153+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:01:19.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:01:19.157+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:01:19.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:01:19.158+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:01:19.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.043 seconds
[2024-11-22T09:01:49.990+0000] {processor.py:153} INFO - Started process (PID=127) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:01:49.991+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:01:49.992+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:01:49.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:01:49.997+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:01:49.997+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:01:49.998+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:01:50.015+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.029 seconds
[2024-11-22T09:02:20.694+0000] {processor.py:153} INFO - Started process (PID=201) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:02:20.697+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:02:20.699+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:02:20.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:02:20.706+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:02:20.705+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:02:20.708+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:02:20.747+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.063 seconds
[2024-11-22T09:02:51.461+0000] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:02:51.463+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:02:51.464+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:02:51.464+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:02:51.468+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:02:51.467+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:02:51.469+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:02:51.486+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.030 seconds
[2024-11-22T09:03:21.952+0000] {processor.py:153} INFO - Started process (PID=381) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:03:21.954+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:03:21.956+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:03:21.956+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:03:21.961+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:03:21.961+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:03:21.961+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:03:21.983+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.035 seconds
[2024-11-22T09:03:52.428+0000] {processor.py:153} INFO - Started process (PID=471) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:03:52.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:03:52.430+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:03:52.430+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:03:52.434+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:03:52.434+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:03:52.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:03:52.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.021 seconds
[2024-11-22T09:04:22.948+0000] {processor.py:153} INFO - Started process (PID=545) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:04:22.949+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:04:22.950+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:04:22.950+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:04:22.959+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:04:22.958+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:04:22.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:04:23.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.056 seconds
[2024-11-22T09:04:53.706+0000] {processor.py:153} INFO - Started process (PID=634) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:04:53.709+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:04:53.710+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:04:53.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:04:53.716+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:04:53.716+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:04:53.717+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:04:53.739+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.039 seconds
[2024-11-22T09:05:24.390+0000] {processor.py:153} INFO - Started process (PID=724) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:05:24.391+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:05:24.395+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:05:24.395+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:05:24.403+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:05:24.402+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:05:24.406+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:05:24.431+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.046 seconds
[2024-11-22T09:05:55.263+0000] {processor.py:153} INFO - Started process (PID=798) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:05:55.265+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:05:55.266+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:05:55.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:05:55.281+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:05:55.278+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:05:55.282+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:05:55.324+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.068 seconds
[2024-11-22T09:06:25.730+0000] {processor.py:153} INFO - Started process (PID=888) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:06:25.732+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:06:25.733+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:06:25.733+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:06:25.741+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:06:25.740+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:06:25.741+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:06:25.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.038 seconds
[2024-11-22T09:06:56.458+0000] {processor.py:153} INFO - Started process (PID=978) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:06:56.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:06:56.460+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:06:56.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:06:56.466+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:06:56.465+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:06:56.467+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:06:56.490+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.037 seconds
[2024-11-22T09:07:27.185+0000] {processor.py:153} INFO - Started process (PID=1068) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:07:27.186+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:07:27.189+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:07:27.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:07:27.198+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:07:27.197+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:07:27.199+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:07:27.277+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.099 seconds
[2024-11-22T09:07:58.171+0000] {processor.py:153} INFO - Started process (PID=1142) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:07:58.172+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:07:58.173+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:07:58.173+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:07:58.179+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:07:58.178+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:07:58.179+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:07:58.200+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.033 seconds
[2024-11-22T09:08:29.029+0000] {processor.py:153} INFO - Started process (PID=1231) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:08:29.030+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:08:29.031+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:08:29.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:08:29.036+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:08:29.035+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:08:29.036+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:08:29.054+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.033 seconds
[2024-11-22T09:09:00.025+0000] {processor.py:153} INFO - Started process (PID=1320) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:09:00.026+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:09:00.027+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:09:00.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:09:00.033+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:09:00.033+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:09:00.035+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:09:00.059+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.039 seconds
[2024-11-22T09:09:30.802+0000] {processor.py:153} INFO - Started process (PID=1403) to work on /opt/airflow/dags/django_sample.py
[2024-11-22T09:09:30.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/django_sample.py for tasks to queue
[2024-11-22T09:09:30.806+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:09:30.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/django_sample.py
[2024-11-22T09:09:30.812+0000] {logging_mixin.py:137} INFO - [2024-11-22T09:09:30.812+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/django_sample.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/django_sample.py", line 46
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
[2024-11-22T09:09:30.813+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/django_sample.py
[2024-11-22T09:09:30.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/django_sample.py took 0.037 seconds
