[2024-11-23T04:39:55.982+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: spotify_etl_dag_playlist.spotify_etl_task_playlist scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T04:39:55.988+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: spotify_etl_dag_playlist.spotify_etl_task_playlist scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T04:39:55.989+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-11-23T04:39:55.989+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-11-23T04:39:55.989+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-11-23T04:39:55.997+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): spotify_etl_task_playlist> on 2024-11-22 00:00:00+00:00
[2024-11-23T04:39:56.001+0000] {standard_task_runner.py:55} INFO - Started process 2609 to run task
[2024-11-23T04:39:56.003+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'spotify_etl_dag_playlist', 'spotify_etl_task_playlist', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/spotify_playlist_dag.py', '--cfg-path', '/tmp/tmpfgmqxzey']
[2024-11-23T04:39:56.004+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask spotify_etl_task_playlist
[2024-11-23T04:39:56.045+0000] {task_command.py:388} INFO - Running <TaskInstance: spotify_etl_dag_playlist.spotify_etl_task_playlist scheduled__2024-11-22T00:00:00+00:00 [running]> on host 810d954bd5ae
[2024-11-23T04:39:56.092+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spotify_etl_dag_playlist
AIRFLOW_CTX_TASK_ID=spotify_etl_task_playlist
AIRFLOW_CTX_EXECUTION_DATE=2024-11-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-22T00:00:00+00:00
[2024-11-23T04:39:56.093+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_playlist_dag.py", line 73, in run_etl
    playlist_data = extract_data_from_spotify(song_title)
  File "/opt/airflow/dags/spotify_playlist_dag.py", line 13, in extract_data_from_spotify
    spotify_client = SpotifyClient()
  File "/opt/airflow/dags/spotify_class.py", line 4, in __init__
    client_id = Variable.get("CLIENT_ID")
NameError: name 'Variable' is not defined
[2024-11-23T04:39:56.099+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=spotify_etl_dag_playlist, task_id=spotify_etl_task_playlist, execution_date=20241122T000000, start_date=20241123T043955, end_date=20241123T043956
[2024-11-23T04:39:56.106+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 53 for task spotify_etl_task_playlist (name 'Variable' is not defined; 2609)
[2024-11-23T04:39:56.142+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-11-23T04:39:56.156+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
